### ISSUE TITLE
TG2-Issues are missing the Resource Type

### ISSUE THREAD

**Issue by chicoreus** [tdwg/bdq#136]
The column Resource Type (Single Record/Multi-Record) got ommitted in translating the spreadsheet into the tables for the issues.  Almost all are Single Record, but a few are Multi-Record.  This column is needed for formal representation of the issues in terms of the framework (and could be added back in when translating the issues back from the tabluar issue into a csv file).

**Comment by Tasilee** [comment]
Good pickup Paul. How did we miss that? Alex: Can you handle it via script and I can add the multi-records manually to the result?

**Comment by godfoder** [comment]
I'm not seeing the single vs. Multi-record in any of the spreadsheets, (Tests-Current, Core) where did it go? I can fill in the stub for everything with just Single Record fairly easily, or maybe mark only the Measures multi record?

**Comment by chicoreus** [comment]
Add single record for all the validations and amendments, leave an empty stub for the measures (there aren't many of them to check)?  Should be easy to fill in in a spreadsheet representation.

**Comment by Tasilee** [comment]
The columns were Record Resolution, Term Resolution, Data Dependency and Output type. I can fill them in, but what is the current master? I presume Tests-CORE?

**Comment by godfoder** [comment]
Lee, I created a copy of the last version of the spreadsheet that had those columns in it. It looks like they vanished sometime in mid-september last year. I'll populate the issues with the values from this sheet.

**Comment by godfoder** [comment]
None of the multi-record tests made it into the core set, even our measures are SingleRecord. I will add the value for completeness, but it will just be a default value.
