### ISSUE TITLE
TG2-Remove all prerequisites for validations referencing amendments.

### ISSUE THREAD

**Issue by chicoreus** [tdwg/bdq#138]
Prerequisites for validations (or problems) in the form "This test should be run after the test TG2-AMENDMENT_..." need to be removed, they are wholly superseded by the general principle of Validate/Amend/Validate, that is all validations are run in a pre-amendment phase, then all amendments are run, then all validations are run again.

**Comment by ArthurChapman** [comment]
From Memory, Paul, these were left in for now until we develop a workflow.  We ran out of time to do a workflow, however there are a number of dependencies.  For example if you have amendments that fill in eventDate from day, month and year, it makes no sense to do a validation on eventDate prior to that amendment action.  We did think about whether it was worth adding another field to identify the tests that should be run before the current test, but thought it best handled by the Workflow. The Workflow would be of the basic form VALIDATION->AMENDMENT->VALIDATION, however - there may be more than one such sequence prior to the final VALIDATION, I think we put some of these in to remind us that there were some order in which certain tests should be run.  Once a Workflow has been drawn up, then these could be removed.

**Comment by chicoreus** [comment]
@ArthurChapman  We do need some description (and the framework is mute on this) of workflow ordering for the amendments.  

We don't, however, want any dependencies of amendments on validations or validations on amendments - these are wholly covered by the general principle of validate/amend/validate (1) pre-amendment phase, run all measures and validations/problems, (2) amendment phase run all amendments (with some to be defined ordering of dependencies), and (3) post-amendment phase, run all measures and validations again.  

A description of the quality of the original data can be found by examining the results of the pre-amendement phase.  A description of the quality of the data if all amendments are accepted can be found by examining the results of the post-amendment phase, and a description of how accepting all the amendments might improve the quality of the data can be obtained from comparing the pre- and post- amendment phases.    This works quite cleanly.   

Still to be defined is how to establish ordering in a workflow for running the amendments.  A use case under the framework can define the set of relevant amendments, but the framework is mute on how a mechanism might order amendments (and as we are seeing in the particular set we are defining, that can be quite important).

**Comment by Tasilee** [comment]
While I agree with you Paul about the general validation-amendment-validation process, I agree with Arthur in that until we have an workflow, it does no harm to note specific known dependencies. A good case in point is #132. What is the order/priority among #61, #86, #93 and #132 ?

#61 has no dependencies as if any of #93, 132 or #86 were run, they would standardize it. I'd therefore say a reasonable order is #61, #93 (easiest), #132 then #86? Once we determine this, it needs to be documented as prerequesites (or notes) in related.

**Comment by ArthurChapman** [comment]
This is the one we drew up on the board and that JohnW suggested the most reliable (not simplest) was 
1. Populate from Verbatim (#86)
2. Populate from Start Day of Year/End Day of Year (#132)
3. Populate from year, month, day (#93)

This is the reverse of what you are suggesting, Lee

**Comment by chicoreus** [comment]
@Tasilee "it does no harm to note specific known dependencies."  Where it comes to listing the interactions among amendments, I agree - indeed it is very important for us to document our assumptions about what order amendments might run in and the consequences of changing that order, and all of the issues you list for considering dependencies are amendments.  I'm only concerned about including validations as dependencies of amendments.

@ArthurChapman As I recall, the rationale @tucotuco had for verbatim then start/end day, then y/m/d, was that these are in descending order of potential richnesss.   Verbatim date can contain ranges that span a year, as well as ranges within a year, and individual days (and discontinuous ranges that can't be represented as ISO dates.  Year plus start and end day is less rich, it can represent an individual day or a range of days, but only within one year.  Year, month, day is the least rich, it can represent an individual day, an interval one month long, or an interval one year long, but not arbitrary ranges of days within a year, or arbitrary ranges of days from year to year.  Thus giving each amendment a prerequisite of an empty dwc:eventDate, and running them in the order you list gives the least chance of information loss about date ranges when proposing a value for the eventDate.

**Comment by Tasilee** [comment]
My point: ""it does no harm to note specific known dependencies" and @chicoreus "I'm only concerned about including validations as dependencies of amendments." **Noted**
