### ISSUE TITLE
Annual Report for 2017 

### ISSUE THREAD

**Issue by ArthurChapman** [tdwg/bdq#14]
The DQIG Annual Report for 2017 has been published on the [GitHub Wiki](https://github.com/tdwg/bdq/wiki/Annual-Report-TDWG-Data-Quality-Interest-Group-for-2017) and is available for perusal.

**Comment by Tasilee** [comment]
Well done Arthur









[image: untitled]



*Lee Belbin*

Science Advisor
Atlas of Living Australia
National Research Collections Australia, National Collections & Marine
Infrastructure, CSIRO *|* Clunies Ross Street, Acton ACT 2601 *|*
GPO Box 1700, Canberra  ACT  2601

Phone: +61 0419 374 133 *| *lee.belbin@csiro.au <leebelbin@gmail.com> *|*
www.ala.org.au *|*  http://www.csiro.au/en/Research/Collections
