### ISSUE TITLE
Microsoft 10 and "Creation Date"

### ISSUE THREAD

**Issue by ArthurChapman** [tdwg/bdq#144]
I am not sure where this issue fits, but it is a Data Quality Issue and that one that will affect data (especially photo data) imported into Citizen Science databases.  Microsoft - for some reason changes the "Creation Date" whenever a file is copied onto Microsoft.  So if you load your photos onto your Laptop or Desktop before uploading to eBird, ALA, Flickr or anywhere else - it won't be the "Date Taken" that is uploaded but the "Creation Date" created by Microsoft. If you look on your Laptop or Desktop - the Creation Date will be the data downloaded from your camera not the Date Taken.  In Properties - you should be able to find the Date Taken under the "Details" Tab.  You can change the Date Created manually or there is software available that will correct the Creation Date a directory (including subdirectories) at a time. I have tried one such software (File Date Corrector) and it works well.  There may be other options available.

I understand that the same happens with Macs but I have no experience of that.

**Comment by Tasilee** [comment]
Thanks @ArthurChapman but unless the issue is exposed via Darwin Core terms, we won't be able to detect it. I presume you mean the difference between the file creation date vs the EXIF "Date/time original"?

**Comment by Tasilee** [comment]
I agree @ArthurChapman that this seems a reasonable location to post such issues but it also raises the question of how we will generate a snapshot of the agreed TG2 tests-assertions to state "this is v1".  "CONFIRMED" is certainly Step 1. An issue for Sunday 26th 2018.
