### ISSUE TITLE
TG2 - Script to translate GitHub issues to CSV file 

### ISSUE THREAD

**Issue by Tasilee** [tdwg/bdq#157]
We need a mechanism to take the parameters of the tests to CSV. In the process 

~~1. Remove “Resource type”~~
1. Remove “Term-Actions”
1. Add GUIDs to those that are missing
1. Separate the Output type, dwc:terms and actions into separate columns

Order perhaps 
1. Label
1. Description or Fail description and Pass description
1. Examples
1. Output type label
1. dwc:terms label
1. Dwc:class
1. Dwc:terms
1. Action
1. Warning type
1. DQ Dimension
1. Notes
1. Test prerequisites
1. References
1. Example implementation (MECHANISM)
1. Link to specification source code
1. Source of the test

**Comment by chicoreus** [comment]
Resource Type is a required framework element.

I think we've got code lying around to do this.  Haven't found it yet though.

**Comment by chicoreus** [comment]
Whoever works on this needs to coordinate with Kurator, we have ffdq-api code that takes this spreadsheet and generates test code stubs and rdf from it, so we need to make sure that the csv fits those expectations, or we modify the Kurator code.

Discussed at 5:30 meeting TDWG 2018, include Matt Collins @mjcollin  on this issue.

**Comment by chicoreus** [comment]
Found the code to do this, updating to get the csv output in the form expected for input by kurator-ffdq tests-util.sh (which can produce both an rdf representation of the tests and stub java methods).  Will get that code checked in somewhere.

**Comment by chicoreus** [comment]
Ran the current kurator-org/bdq_issue_to_csv code on a download of the current set of CORE issues, result in attached text file (haven't tested if this converts to RDF yet, but it should.
[issuelist_2019Feb27.txt](https://github.com/tdwg/bdq/files/2911820/issuelist_2019Feb27.txt)

**Comment by chicoreus** [comment]
Closing, as this is provided by kurator-org/bdq_issue_to_csv and that code has been used 6 times to generate and update the csv list of files TG2_tests.csv https://github.com/tdwg/bdq/commits/master/tg2/core/TG2_tests.csv   That file can be used to generate rdf descriptions of the tests in the framework vocabuluary. @Tasilee also has code he has been using to generate a separate spreadsheet of tests not as closely matched to the framework.
