### ISSUE TITLE
TaxonRank

### ISSUE THREAD

**Issue by ArthurChapman** [tdwg/bdq#159]
I was asked by someone at TDWG (and there was some discussion in one of the SPNHC meetings) if we had a test for taxonRank.  What do you think people? Should we add:

VALIDATION_TAXONRANK_EMPTY, 
VALIDATION_TAXONRANK_NOTSTANDARD
AMENDMENT_TAXONRANK_STANDARDIZED

**Comment by robgur** [comment]
Standardized according to what taxonomic authority?  Do you want to go down
this road?

**Comment by ArthurChapman** [comment]
Don't each of the Codes have a standard list of Ranks?  I know there are other ranks that are used - but if they are ones not in the Code. The Standardizing would change ssp. to subsp. or (vice versa, I can't remember) and things like that.  If it was one that can't be changed, then an assertion is made to say it could not be so amended,

**Comment by tucotuco** [comment]
I think we definitely want this test, and I do not think it depends on any taxonomic authority, but rather on the codes.

**Comment by KevinThiele** [comment]
My understanding of the botanical code at least is that there are Code-mandated ranks, but the Code allows inter-ranks to be created more or less willy-nilly:

From https://en.wikipedia.org/wiki/Taxonomic_rank#Ranks_in_botany: "There is an indeterminate number of ranks, as a taxonomist may invent a new rank at will, at any time, if they feel this is necessary. In doing so, there are some restrictions, which will vary with the nomenclature code which applies."

I'm not sure if these non-Code ranks would be regarded as NOTSTANDARD.

**Comment by KevinThiele** [comment]
Note with this comment I'm not saying this is a good idea! Personally, I reckon we should retract to only the Linnaean ranks, then use rank-free taxa (or better still, a phylogeny) for anything else. But that's another conversation.

**Comment by ArthurChapman** [comment]
Looking through the Botanical Code - ranks are not actually mandated

2.1. Every individual organism is treated as belonging to an indefinite number of taxa at consecutively subordinate ranks, among which the rank of species is basic.
3.1. The principal ranks of taxa in descending sequence are: kingdom (regnum), division or phylum (divisio or phylum), class (classis), order (ordo), family (familia), genus (genus), and species (species). Thus, each species is assignable to a genus, each genus to a family, etc.
4.1. The secondary ranks of taxa in descending sequence are tribe (tribus) between family and genus, section (sectio) and series (series) between genus and species, and variety (varietas) and form (forma) below species.
4.2. If a greater number of ranks of taxa is desired, the terms for these are made by adding the prefix “sub-” to the terms denoting the principal or secondary ranks. An organism may thus be assigned to taxa at the following ranks (in descending sequence): kingdom (regnum), subkingdom (subregnum), division or phylum (divisio or phylum), subdivision or subphylum (subdivisio or subphylum), class (classis), subclass (subclassis), order (ordo), suborder (subordo), family (familia), subfamily (subfamilia), tribe (tribus), subtribe (subtribus), genus (genus), subgenus (subgenus), section (sectio), subsection (subsectio), series (series), subseries (subseries), species (species), subspecies (subspecies), variety (varietas), subvariety (subvarietas), form (forma), and subform (subforma).
4.3. Further ranks may also be intercalated or added, provided that confusion or error is not thereby introduced.

These terms are all well covered by the GBIF Vocabulary at http://rs.gbif.org/vocabulary/gbif/rank.xml

The Zoological Code doesn't say much at all about Ranks - and what they do say doesn't contradict the Botanical Code.  Similarly for the Virus Code

By creating a Test for NON_STANDARD - if it does not fit one of those Ranks (in the GBIF doc) an annotation is made - it is not saying it is Wrong - just that it is not one of those Standard Ranks.  For the STANDARDIZED test - GBIF includes a number of other language equivalents that could be amended.

At TDWG2018 - the issue of taxonRank was raised in several discussions and several people recommended including such a test.

**Comment by ianengelbrecht** [comment]
Yup, I agree that this would be good test to include. The annotation would include the authority that scientificName is checked/standardized against.

**Comment by rdstevenson10** [comment]
I also agree. As part of cleaning a data set one might want to use services to fill in missing ranks.

**Comment by Tasilee** [comment]
So, on the basis of this discussion, are amendments suggested for #161, #162 and #163 to close this issue?

**Comment by ArthurChapman** [comment]
I don't think so - the GBIF reference includes all the relevant terms in the Vocabulary - and several people want the tests.  I wrote the tests with the knowledge of what I wrote above, so I don't think any change is needed.
