### ISSUE TITLE
TG2-Some terminology for Target source authority

### ISSUE THREAD

**Issue by ArthurChapman** [tdwg/bdq#160]
In most of the Test Prerequisites we refer to "specified target source authority" (#20 #21 #22 #25 #26 #27 #28 #38 #41 #45 #46 #48 #50 #53 #56 #57 #59 #60 #62 #63 #70 #71 #73 #77 #80 #81 #83 #90 #91 #94 #95 #97 #106 #115 #116 #118 #122 #123 #133 #139) or "specified source vocabulary" (#63 #104), 

but in many of the descriptions we use "designated source authority" (#22 #28 #63 #70 #77 #81 #83 #122 #123 #139 ) or "designated geographic authority" (#118 )

From the above we are very consistent in the Test Prerequisite - perhaps we should change #63 and #104 .

In the Descriptions we are consistent with "designated" - should we change this to "specified" (we don't have specified in any description at the moment) and should we change #118 to "designated source authority"

**Comment by Tasilee** [comment]
I would default universally (examples, reference, notes) to the simpler "specified authority"

**Comment by tucotuco** [comment]
I agree.

**Comment by ArthurChapman** [comment]
OK - I will change them all to specified target source authority and close this issue

**Comment by ArthurChapman** [comment]
All have been altered to refer to "specified" source authority
