### ISSUE TITLE
DIMENSION in the tests

### ISSUE THREAD

**Issue by ArthurChapman** [tdwg/bdq#166]
We have a field in the Tests called DIMENSION (NAME, SPACE, TIME, OTHER)

All the NAME tests use the Darwin Core Class: Taxon - except one (#106 ) that is Taxon and Identification, 

All the TIME tests use the Darwin Core Class: Event

All the SPACE tests use the Darwin Core Class: Location

The OTHER - five use the Darwin Core Class: Occurrence
                   - eight use the Darwin Core Class: Record_level Terms

#72 a NOTIFICATION that has 3 Dimensions (Space, Time, Name) and refer to the Darwin Core Class "Record Level".  This could better be OTHER

The MEASURE tests which have Darwin Core Class :"All"  except for one (#140 ) which as Darwin Core Class: Event

I think this gives us a lot of Duplication - instead of DIMENSION (NAME, SPACE, TIME, OTHER) which have been great as a working tool - and we can still use those labels in GitHub, I see little value in including the field in the tests - and can just use the Darwin Core Classes (Taxon, Event, Location, Occurrence, Identification, Record_level Terms, and All)

**Comment by ArthurChapman** [comment]
This would also save us having to define DIMENSION, NAME, SPACE, TIME, OTHER in the Vocabulary

**Comment by chicoreus** [comment]
The name "Dimension" is confusing, as a fundamental concept in the Framework is Dimension, meaning data quality dimension, while the values listed here are categories of Information Elements.   The labels applied to the tests in the github issue tracker with these values (NAME, TIME, etc) have definitely been valuable in clustering tests of interest as we've been discussing them, so perhaps there's an issue here to put against TG1 to provide a framework element to categorize Information Elements (i.e. an Information Element having properties of label (e.g. Coordinate), specific terms (e.g. dwc:decimalLatitude, dwc:decimalLongitude, dwc:geodeticDatum, dwc:coordinateUncertaintyInMeters, dwc:coordinatePrecision), and category (e.g. SPACE).   

This would allow TG2 to define InformationElement category values such as SCINAME, TIME, SPACE, OTHERDWC).

**Comment by tucotuco** [comment]
Might there be merit in using Darwin Core classes among the clustering
categories?

**Comment by ArthurChapman** [comment]
@chicoreus I agree that if we keep them we should change DIMENSION to something else so as to not confuse with Framework.  I also find TIME confusing as it refers to Event rather than time and in fact we have very few references to dwc:time. 

@tucotuco for me - yes - I believe we can do without and just follow Darwin Core Classes. I like keeping at simple as possible. I would like to hear what @Tasilee and others think

**Comment by Tasilee** [comment]
As long as we can easily categorise each test as NAME, SPACE, TIME and OTHER **from** Darwin Core Class, then those terms are redundant.
