### ISSUE TITLE
New Label "Test"

### ISSUE THREAD

**Issue by tucotuco** [tdwg/bdq#167]
I think it would be helpful to have a single label that could be used to get exactly the list of issues that are definitions of tests from the repository issue tracker.  I propose that it be called "Test" or "Assertion" or "Tests and Assertions" and that is be added to everything that is one. That way a URL could be shard that showed people a list of them all. I wuld be happy to add this if there is a consensus that it is useful. I would use it right away in a discussion in the Darwin Core Questions and Answers issues about data quality.

**Comment by ArthurChapman** [comment]
I'd say go ahead John.  I would just use "Test"  as they don't as yet include any assertions.

**Comment by Tasilee** [comment]
Just back online: I'll add "Test"

**Comment by tucotuco** [comment]
Done. Closing.
