### ISSUE TITLE
Expected Response versus Pass/Fail

### ISSUE THREAD

**Issue by tucotuco** [tdwg/bdq#175]
Our tests and assertions are missing consistent specifications of the expected responses. Sometimes we include that information in a Description, sometimes in the Examples, sometimes we include a Fail description and Pass description (for Notifications and Validations). Those descriptions strike me as odd. Wouldn't it be better, and "closer to code" to simply have an "Expected response" column for all our tests and assertions? As a coder I would find that easier to grasp. I trip on the logic that a notification should have a pass or fail condition, for example. The tests don't pass or fail, they simply run and return results. For all Amendments, Notifications, they return either True or False, for measures, they return a number. Here are a few examples of what I propose.  

For TG2-NOTIFICATION_ESTABLISHMENTMEANS_NOTEMPTY:

Expected response: INTERNAL_PREREQUISITES_NOT_MET if there is no field dwc:establishmentMeans in the input, False if field dwc:establishmentMeans is EMPTY, otherwise True.

rather than:

Fail Description: The field dwc:establishmentMeans is not EMPTY
Pass Description: The field dwc:establishmentMeans is EMPTY
Test Prerequisites: The field dwc:establishmentMeans is present in the record.

For TG2-VALIDATION_DAY_NOTSTANDARD:

Expected response: INTERNAL_PREREQUISITES_NOT_MET if there is no field dwc:day, False if the value of the field dwc:day is an integer between 1 and 31 inclusive, otherwise True. 

rather than:

Fail Description: The value of dwc:day is not an integer between 1 and 31 inclusive
Pass Description: The value of dwc:day is an integer between 1 and 31 inclusive
Test Prerequisites: The field dwc:day is not EMPTY.

For TG2-VALIDATION_GENUS_NOTFOUND:

Expected response: INTERNAL_PREREQUISITES_NOT_MET if there is no field dwc:genus in the input or if the field dwc:genus is EMPTY, EXTERNAL_PREREQUISITES_NOT_MET if the supplied source authority does not provide a response, True if the value of dwc:genus was not found as a value at the rank of genus in the specified source authority, otherwise False.

rather than:

Fail Description: The value of dwc:genus was not found as a value at the rank of genus in the specified source authority
Pass Description: The value of dwc:genus was found as a value at the rank of genus in the specified source authority
Notes: The purpose of this test is to check whether the value is a name that is a result of a nomenclatural act at this rank. This excludes unpublished names, misspellings and vernacular names. It is expected that the test will designate the source authority against to check. The same test might return distinct results when using distinct source authorities.
Test Prerequisites: A specified target source authority. The field dwc:genus must not be EMPTY.

Looking at the tests this way makes me nervous about many of those of output type Measure, for example TG2-MEASURE_VALIDATIONTESTS_COMPLIANT (https://github.com/tdwg/bdq/issues/135). That one doesn't have a well-defined expected response. If we want to go in this direction in general, I propose we revisit the measure tests, make their expected results explicit.

**Comment by ArthurChapman** [comment]
@tucotuco - I like your thinking.  I have never liked the "Pass Description/Fail Description" and have done a lot of thinking on how we could avoid this.  And true - perhaps @chicoreus has given thought to the expected response (Respose.status in his terms), but it is an area we have had very little discussion. 

I wonder though if we could go one step further and tie the response more to the Framework by using COMPLIANT and NOT_COMPLIANT rather than True and False e.g. using your examples

For **TG2-NOTIFICATION_ESTABLISHMENTMEANS_NOTEMPTY**:

Expected response: PREREQUISITES_NOT_MET if there is no field dwc:establishmentMeans in the input, NOT_COMPLIANT if field dwc:establishmentMeans is EMPTY, otherwise COMPLIANT.

For **TG2-VALIDATION_DAY_NOTSTANDARD**:

Expected response: PREREQUISITES_NOT_MET if there is no field dwc:day, NOT_COMPLIANT if the value of the field dwc:day is an integer between 1 and 31 inclusive, otherwise COMPLIANT.

etc.

**Comment by ArthurChapman** [comment]
With respect to Measures - isn't the response a number?  i.e. the number of tests that are COMPLIANT, number of tests that are NOT_COMPLIANT?

**Comment by tucotuco** [comment]
I think I rather like the COMPLIANT, NOT_COMPLIANT responses.

I guess the Measures are much more clear after defining responses in terms of COMPLIANT and NOT_COMPLIANT - another reason to do so.

**Comment by Tasilee** [comment]
OK, anything to simplify the system would be good. I suspect going through all the tests will clarify any issues. The MEASUREs are a (higher-level) review of VALIDATIONS and AMENDMENTs with one odd TG2-MEASURE_EVENTDATE_PRECISIONINSECONDS.

**Comment by chicoreus** [comment]
The concept @tucotuco is looking for is called Specification in the framework.  You can see this in the code which generates the csv from the github issues tables, it combines the fail response with the pass response with the prerequisites to form a specification, see: https://github.com/kurator-org/bdq_issue_to_csv/blob/d9f575846298166187f0e1bfe324dd354bd09cd7/src/main/java/org/kurator/issueconverter/BDQConvert.java#L284

**Comment by chicoreus** [comment]
@ArthurChapman yes, for each test which is a Validation at the singlerecord level, there is a corresponding Measure of the proportion of records which are COMPLIANT at the multirecord level.

**Comment by chicoreus** [comment]
In the QA case in the framework, this measure is always at either 100% or there are no records in the result (as in QA, all non-compliant, thus not fit for use, records are filtered out.  In the QC, case in the framework these measures of proportion compliant have arbitrary values (and can have different values in pre-amendment and post-amendment phases, as proposed amendments are expected to improve the fittness for use (thus the proportion of records that are compliant for validations for the use case increases))

**Comment by ArthurChapman** [comment]
@chicoreus and there is the difference with the Tests and Assertions - we are identifying the NOT_COMPLIANT as problem records.  The QA is looking for records that are suitable for a (positive) use. but we are looking for records that have a problem.  My hope is that for most , if not all the tests, these records will be eventually fixed (or annotated as to why they could not be fixed) and thus should seldom appear in the QA. There is no reason for many of these "errors" to remain if the data is cleaned satisfactorily - once it gets to using the Framework for filtering records for a particular use, I am hoping that we don't have Latitudes of +95, or dates that are impossible, etc. and that is the aim of the Tests,  But then - I am ever the optimist!

**Comment by ArthurChapman** [comment]
If you are in favour of the suggestion of @tucotuco as modified in the comments - could you please add a thumbs up to the issue, if you are against, please add a thumbs down so we can progress this issue asap

**Comment by chicoreus** [comment]
Noting that "Expected Response" has been propagated throughout the issues, and the bdq_issue_to_csv code supported the generation of the ffdq:Specification from "Expected Response" instead of Pass and Fail rows in the markdown as of https://github.com/kurator-org/bdq_issue_to_csv/commit/5b996274ffc8db4bb1dd542fd0c605dfdeb99cb9

It feels like this issue can be closed.

**Comment by ArthurChapman** [comment]
@chicoreus Agreed

**Comment by Tasilee** [comment]
@chicoreus and @ArthurChapman: Closed.
