### ISSUE TITLE
TG2 Check Test References for DwC term links

### ISSUE THREAD

**Issue by tucotuco** [tdwg/bdq#184]
I found that some tests have (incorrect) links to Darwin Core terms in the References, while others do not. It isn't clear why this would ever be needed. It seems extraneous to me. If so, then they should all be purged. If not, then they should be included consistently and made to resolve correctly.

Example: Substitute https://dwc.tdwg.org/terms/#dwc:endDayOfYear in place of https://rs.tdwg.org/dwc/terms/index.htm#endDayOfYear in issue #131.

**Comment by chicoreus** [comment]
It doesn't seem that we need them, dwc: is after all shorthand for the resolvable uri...

**Comment by ArthurChapman** [comment]
All removed.
