### ISSUE TITLE
TG2-Issues toward the standard

### ISSUE THREAD

**Issue by Tasilee** [tdwg/bdq#193]
This is a list of issues and associated discussion to bring the work of TG2 to a TDWG standard.

**Comment by Tasilee** [comment]
From @chicoreus in regards interpreting values:

"Test implementations MAY accept all parameters as strings.  The test Specifications include the phrase "interpreted as" to indicate to implementors that data type conversion from string serializations of Darwin Core may be needed.  The test descriptions are agnostic to where type conversion is performed in an implementation."

**Comment by Tasilee** [comment]
From our Zoom discussion, we have some of the basic resources

1. The Excel file File that contains Test specification, test data and vocabulary. The master for these is in github with the exception of the test data.
2. Framework
3. Background context
4. Guidelines for implementers
5. Guidelines for DQ reports.

**Comment by Tasilee** [comment]
We have started writing a standards document and have most of the outline of the structure and some content. We could use this Issue as a publicly exposed area for comments about this document. I will add a comment that exposes the current structure..

**Comment by Tasilee** [comment]
![Capture](https://github.com/tdwg/bdq/assets/6656350/292a2b50-93a5-4919-be32-c1bd46c213ec)

**Comment by chicoreus** [comment]
I thing we can close this one, replaced by #300
