### ISSUE TITLE
TG2 - no flag for DATE_INVALID?

### ISSUE THREAD

**Issue by ymgan** [tdwg/bdq#198]
Hello,

The OBIS data quality project team is looking at the [tests and assertions](https://docs.google.com/spreadsheets/d/1uwnUtcMSe88AytUt_mSepeLTz54tMvV9llO2pBnObhE/edit#gid=1444049182) by this task group and we want to align some of existing data quality tests and flags with what is documented in the tests and assertions sheet.

We found out that there are `DAY_INVALID` and `MONTH_INVALID` in the tests and assertions but not `DATE_INVALID`? I am wondering if there is a reason behind this? 

And a minor question - is the `Variable` field in the google sheet equals to the quality flag?

Thank you so much!!

cc: @pieterprovoost

**Comment by tucotuco** [comment]
Hi @ymgan, I think this is the test you are looking for:

https://github.com/tdwg/bdq/issues/66
