### ISSUE TITLE
how are the default values of the parameters determined?

### ISSUE THREAD

**Issue by ymgan** [tdwg/bdq#202]
Hello,

May I know how are the default values of the parameters determined for the test specification? 

For example: [TG2-VALIDATION_YEAR_INRANGE #84](https://github.com/tdwg/bdq/issues/84) 
How did the task group arrive at bdq:earliestDate="1500"; bdq:latestDate=current year for the default parameters?

Thanks a lot!!

**Comment by tucotuco** [comment]
@ymgan The discussion about 1500 as a default can be found beginning at [this comment](https://github.com/tdwg/bdq/issues/84#issuecomment-1157627028).

**Comment by ymgan** [comment]
Thank you so much @tucotuco !! Does that mean that **all** of the default parameters are based on use cases from aggregators (e.g. GBIF, ALA, iDigBio)?

**Comment by tucotuco** [comment]
> Thank you so much @tucotuco !! Does that mean that **all** of the default parameters are based on use cases from aggregators (e.g. GBIF, ALA, iDigBio)?

@ymgan No, it doesn't necessarily mean that. Some defaults are derived from geophysical parameters, such as minimum and maximum elevation in meters, maximum coordinate uncertainty in meters, etc. Are there specific terms that concern you?

**Comment by ymgan** [comment]
Thanks @tucotuco !! The reason I opened this issue is, the [OBIS data quality project team](https://github.com/iobis/quality-taskteam) that I am chairing is tasked to align the [BDQ TG2 test specifications](https://github.com/tdwg/bdq/issues?q=is%3Aissue+is%3Aopen+label%3ATest) with the tool that is being used by OBIS. The task for this team is to determine the parameters of the tests implemented in the chosen tool. But there are 3 main tools that are currently being used by OBIS communities: [obistools](https://github.com/iobis/obistools), [BioCheck tool](https://github.com/EMODnet/EMODnetBiocheck) and [obis-qc](https://github.com/iobis/obis-qc) (see: https://github.com/gbif/portal16/issues/1837) 

However, due to the lack of resources from OBIS Secretariat and OBIS nodes who maintain those tools, I do not yet know which tool we should be looking at because I have not have a chance to speak to them. These are all different tools implementing different tests and having different quality flags ... That being said, I do not yet know which test specifications exactly we should be looking at. But I wanted to have some understandings on how parameters were being determined in the tests because I could not go through all of the comments of every issue with parameters.

**Comment by tucotuco** [comment]
Understood. Keep in mind that parameters that have defaults can be overridden for specific by setting the parameter.
