### ISSUE TITLE
Recognition of geodeticDatum Field by IPT

### ISSUE THREAD

**Issue by marcelooyaneder** [tdwg/bdq#203]
Hello, recently we have published biodiversity data in GBIF using the georeferencing process recommended by the publication ([georeferencing best practices](https://docs.gbif-uat.org/georeferencing-best-practices/1.0/en/)), using the georeferencing Calculator tool. In addition to the field "coordinateUncertaintyInMeters", this tool provides other data such as the datum. For our publication, we used the datum "WGS84" and it was published in our database as it is delivered by the Calculator, "(WGS84) World Geodetic System 1984". However, when analyzing our data later in GBIF under "Issues and Flags", we found that this datum is not recognized by the IPT.

While the solution is to change the datum to "WGS84" or "EPSG:4326", would it be possible to add the value "(WGS84) World Geodetic System 1984" to the allowed dictionary in IPT? The georeferencing Calculator is recognized as one of the official tools that add quality to databases related to the georeferencing process. Additionally, we believe that it would be useful to disseminate this information to the nodes, as we stumbled upon this issue while generating a quality report for our data published in GBIF.

Best regards,

Marcelo Oyaneder Labarca - [marcelo.oyaneder@usach.cl](mailto:marcelo.oyaneder@usach.cl)
Paulette Naulin Gysling - [pnaulin@uchile.cl](mailto:pnaulin@uchile.cl)

---------------------------------------------

Hola, recientemente hemos publicado datos de biodiversidad en GBIF utilizando el proceso de georreferenciación recomendado por la publicación ([georeferencing best practices](https://docs.gbif-uat.org/georeferencing-best-practices/1.0/en/)), utilizando la herramienta georreferencing Calculator, de esta se entrega además del campo coordinateUncertaintyInMeters otros datos como el datum, para el caso de nuestra publicación hemos utilizado el datum wgs84, este se ha publicado en nuestras bases tal como lo entrega la calculado "(WGS84) World Geodetic System 1984", pero al analizar nuestros datos posteriormente en GBIF buscando "Issues and Flags" hemos encontrado que este datum no se reconoce por el IPT. 

Si bien la solución es cambiar el datum a "WGS84" o "IPSG:4326", ¿sería posible agregar el valor "(WGS84) World Geodetic System 1984" al diccionario permitido IPT?, siendo que la calculadora es reconocida como una de las herramientas oficiales que agrega calidad a las bases de datos relacionado al proceso de georreferenciación. 

Además creemos que sería util generar difusión sobre esta información a los nodos, ya que se encontró de casualidad, mientras generabamos un informe de calidad de nuestros datos publicados en GBIF.

Saludos.
Marcelo Oyaneder Labarca - [marcelo.oyaneder@usach.cl](mailto:marcelo.oyaneder@usach.cl)
Paulette Naulin Gysling - [pnaulin@uchile.cl](mailto:pnaulin@uchile.cl)

**Comment by timrobertson100** [comment]
Thanks for notifying me on this issue @ArthurChapman, and @marcelooyaneder for raising it.

I think this might have been reported elsewhere to GBIF as I see yesterday @MattBlissett committed [a fix](https://github.com/gbif/parsers/commit/8383b3e72bbd493047eee16fd4e18a4da35b0a45) on the GBIF parsers project. When that is deployed in the next release GBIF.org will correctly interpret the data.

The reference to the IPT might be a slight misunderstanding as the IPT itself doesn't parse this field but simply includes whatever was mapped from the source data in the Darwin Core Archive it produces.

I think this could be closed now as fixed, and thanks again @marcelooyaneder
