### ISSUE TITLE
TG2-Test Template

### ISSUE THREAD

**Issue by Tasilee** [tdwg/bdq#211]
| TestField | Value |
| ----- | ----- |
| **GUID** |  |
| **Description** |  |
| **TestType** |  |
| **Darwin Core Class** |  |
| **Information Elements ActedUpon** |  |
| **Information Elements Consulted** |  |
| **Expected Response** |  |
| **Data Quality Dimension** |  |
| **Term-Actions** |  |
| **Parameter(s)** | |
| **Source Authority** |  |
| **Specification Last Updated** |  |
| **Examples** |   |
| |  |
| **Source** |  |
| **References** |  |
| **Example Implementations (Mechanisms)** |  |
| **Link to Specification Source Code** |  |
| **Notes** |  |

**Comment by ArthurChapman** [comment]
A new Test Template has been added to the Issues for requesting a new test of fr requesting a test change. Thes can be found when clicking on New Issue
