### ISSUE TITLE
Broken link to Open Context

### ISSUE THREAD

**Issue by ekansa** [tdwg/bdq#294]
Hello! 

I noticed a broken link to Open Context (see issue report here: https://github.com/sibbr/DarwinCoreBrasil/issues/194)

Please update the Open Context URIs here:
https://github.com/tdwg/bdq/blob/a89903ba7906edf2fcac4b5da473c8a23abb5c7c/tg2/core/testdata/Testdata_all.csv?plain=1#L167

and here:

https://github.com/tdwg/bdq/blob/a89903ba7906edf2fcac4b5da473c8a23abb5c7c/tg2/core/TG2_tests.csv?plain=1#L16

In those two files, please replace "https://opencontext.org/subjects/768A875F-E205-4D0B-DE55-BAB7598D0FD19" (ends in an invalid UUID,  leads to a 404 error) with a valid Open Context URI "https://opencontext.org/subjects/e54377f7-4452-4315-b676-40679b10c4d9" (that is actually used with an Open Context / VertNet integration).

**Comment by chicoreus** [comment]
This pertains to an example in #40

**Comment by chicoreus** [comment]
Changed in #40.  master spreadsheet for validation data updated, will propagated to validation data csv on next update.
