### ISSUE TITLE
New Test Template

### ISSUE THREAD

**Issue by ArthurChapman** [tdwg/bdq#298]
## New test

* Submitter: 
* Efficacy Justification (why is this test necessary?): 
* Demand Justification (name at least two organizations that independently need this test): 
* Stability Justification (what concerns are there that this might affect existing implementations?): 
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: 

Proposed attributes of the new term:

* Test name (in all UPPERCASE, in the pattern TYPE_INFORMATIONELEMENT_STATUS). A human readable label identifying the test:
* skos:preflabel (English, not normative): 
* Description (English, not normative):
* Test type (Validation, Amendment, Issue, Measure):
* Darwin Core Class (e.g., Occurrence, Event, Location, Taxon, not normative): 
* Information Elements Acted Upon (e.g. Darwin Core Terms, normative):
* Information Elements Consulted (e.g. Darwin Core Terms, normative):
* Specification (normative):
* Data Quality Dimension (normative):
* Date Last Updated (normative): 
* Parameter(s) (normative):
* Source Authority or Authorities (not normative): 
* References (not normative):
* Usage comments (recommendations regarding content, etc., not normative): 
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative):

**Comment by ArthurChapman** [comment]
Should these other terms be included or not?

* Usage comments (recommendations regarding content, etc., not normative): 
        =Example Implementations (Mechanisms). Known Mechanisms with implementations of the test.
* Link to Specification Source Code (not informative)
* Examples (not normative): 
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative):

**Comment by tucotuco** [comment]
I would vote for using the Usage comments from the old template to replace Notes on the proposed new template.

When new tests are proposed, there would not be any links to implementation source code. In test change issues, there would be. I would leave it off of this template.

I don't think we have examples other than the test data and results of running the tests, so I would scratch that one.

Replaces needs to stay there as is. It is normative.

**Comment by ArthurChapman** [comment]
Updated in accord with @tucotuco comment

**Comment by tucotuco** [comment]
Template created.
