### ISSUE TITLE
Last name correction in the Wiki home page

### ISSUE THREAD

**Issue by allankv** [tdwg/bdq#3]
My last name is incorrect in the wiki home page.
The correct is **Veiga** instead Viega.

**Comment by ArthurChapman** [comment]
Thanks Allan

I was on my phone and couldn't check.

My apologies- will change.

Arthur

On 30 October 2016 5:55:10 AM AEDT, Allan Koch Veiga <notifications@github.com> wrote:
>My last name is incorrect in the wiki home page.
>The correct is **Veiga** instead Viega.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tdwg/bdq/issues/3

Arthur Chapman
Australian Biodiversity Information Services
PO Box 35
Ballan Vic  3342
Australia
biodiv_2@achapman.org

**Comment by allankv** [comment]
It's okay, no problem. Thank you.
